"""Git automation for self-heal / augment output.

Every proposal is delivered via **branch + PR** — never a silent commit to the
working branch. This module is deliberately thin: it shells to ``git`` and the
``gh`` CLI so it works the same in CI and locally, and it refuses to operate on the
default branch directly.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from skillsmith_core.config import GitConfig
from skillsmith_core.models import ProposedChange


class GitError(RuntimeError):
    pass


@dataclass
class PRResult:
    branch: str
    committed: bool
    pr_url: str | None
    dry_run: bool


def _git(repo: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args], capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        raise GitError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def _has_gh() -> bool:
    import shutil

    return shutil.which("gh") is not None


def current_branch(repo: Path) -> str:
    return _git(repo, "rev-parse", "--abbrev-ref", "HEAD")


def default_branch(repo: Path) -> str:
    try:
        ref = _git(repo, "symbolic-ref", "refs/remotes/origin/HEAD")
        return ref.rsplit("/", 1)[-1]
    except GitError:
        return "main"


def open_pr_for_change(
    repo: Path,
    change: ProposedChange,
    config: GitConfig,
    *,
    apply_diff: bool,
    dry_run: bool = False,
) -> PRResult:
    """Create a branch, optionally apply the diff + commit, and open a PR.

    ``apply_diff=False`` produces a branch carrying only the proposal metadata (the
    human applies the diff during review). ``apply_diff=True`` is reserved for the
    auto-if-tests-pass low-risk tier and still goes through a PR — never a direct
    commit to the working branch.
    """

    slug = _slugify(change.title)
    branch = f"{config.branch_prefix}{change.action_class}/{slug}"

    if dry_run:
        return PRResult(branch=branch, committed=False, pr_url=None, dry_run=True)

    base = current_branch(repo)
    if base == default_branch(repo):
        # Branch off; we never commit proposals onto the default branch.
        pass
    _git(repo, "checkout", "-B", branch)

    committed = False
    if apply_diff and change.unified_diff.strip():
        _apply_unified_diff(repo, change.unified_diff)
        for p in change.touched_paths:
            _git(repo, "add", str(p))
        body = _commit_message(change, config)
        _git(repo, "commit", "-m", body)
        committed = True

    pr_url: str | None = None
    if config.open_pr and _has_gh() and committed:
        proc = subprocess.run(
            [
                "gh",
                "pr",
                "create",
                "--title",
                change.title,
                "--body",
                _pr_body(change),
                *(["--label", ",".join(config.pr_labels)] if config.pr_labels else []),
            ],
            cwd=str(repo),
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode == 0:
            pr_url = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else None

    return PRResult(branch=branch, committed=committed, pr_url=pr_url, dry_run=False)


def _apply_unified_diff(repo: Path, diff: str) -> None:
    proc = subprocess.run(
        ["git", "-C", str(repo), "apply", "--whitespace=nowarn", "-"],
        input=diff,
        text=True,
        capture_output=True,
        check=False,
    )
    if proc.returncode != 0:
        raise GitError(f"failed to apply proposed diff: {proc.stderr.strip()}")


def _commit_message(change: ProposedChange, config: GitConfig) -> str:
    return (
        f"{change.action_class}: {change.title}\n\n"
        f"{change.rationale}\n\n"
        f"Proposed by skillsmith. Reviewed-and-approved required before merge.\n\n"
        f"{config.commit_trailer}\n"
    )


def _pr_body(change: ProposedChange) -> str:
    saving = "" if change.token_delta is None else f"\n\n**Token delta:** {change.token_delta:+d}"
    return (
        f"### {change.title}\n\n"
        f"{change.rationale}{saving}\n\n"
        f"Low-risk tier: `{change.low_risk}`\n\n"
        "<details><summary>Proposed diff</summary>\n\n"
        f"```diff\n{change.unified_diff}\n```\n\n</details>\n\n"
        "_Generated by skillsmith — review before merging. No changes were applied "
        "to your working branch._"
    )


def _slugify(text: str) -> str:
    out = "".join(c if c.isalnum() else "-" for c in text.lower()).strip("-")
    while "--" in out:
        out = out.replace("--", "-")
    return out[:48] or "change"
